<?xml version="1.0" encoding="UTF-8"?>
<definitions name="mgopfserver"
 targetNamespace="http://139.129.41.15:9983/mgopfserver.wsdl"
 xmlns:tns="http://139.129.41.15:9983/mgopfserver.wsdl"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:ns="urn:mgopfserver"
 xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:HTTP="http://schemas.xmlsoap.org/wsdl/http/"
 xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/"
 xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="urn:mgopfserver"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:ns="urn:mgopfserver"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 </schema>

</types>

<message name="mgopfserverRequest">
 <part name="processNum" type="xsd:string"/><!-- ns__mgopfserver::processNum -->
 <part name="host" type="xsd:string"/><!-- ns__mgopfserver::host -->
 <part name="user" type="xsd:string"/><!-- ns__mgopfserver::user -->
 <part name="password" type="xsd:string"/><!-- ns__mgopfserver::password -->
 <part name="dbName" type="xsd:string"/><!-- ns__mgopfserver::dbName -->
 <part name="port" type="xsd:string"/><!-- ns__mgopfserver::port -->
 <part name="algorithmID" type="xsd:string"/><!-- ns__mgopfserver::algorithmID -->
</message>

<message name="mgopfserverResponse">
 <part name="status" type="xsd:int"/><!-- ns__mgopfserver::status -->
</message>

<portType name="mgopfserverPortType">
 <operation name="mgopfserver">
  <documentation>Service definition of function ns__mgopfserver</documentation>
  <input message="tns:mgopfserverRequest"/>
  <output message="tns:mgopfserverResponse"/>
 </operation>
</portType>

<binding name="mgopfserver" type="tns:mgopfserverPortType">
 <SOAP:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="mgopfserver">
  <SOAP:operation style="rpc" soapAction=""/>
  <input>
     <SOAP:body use="encoded" namespace="urn:mgopfserver" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </input>
  <output>
     <SOAP:body use="encoded" namespace="urn:mgopfserver" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </output>
 </operation>
</binding>

<service name="mgopfserver">
 <documentation>gSOAP 2.8.25 generated service definition</documentation>
 <port name="mgopfserver" binding="tns:mgopfserver">
  <SOAP:address location="http://139.129.41.15:9983/mgopfserver.cgi"/>
 </port>
</service>

</definitions>
